---
apiVersion: v1
kind: Namespace
metadata:
  name: minecraft
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: minecraft-server
  name: minecraft-server
  namespace: minecraft
spec:
  replicas: 1
  serviceName: minecraft-server
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      containers:
        - name: minecraft-server
          image: itzg/minecraft-server
          imagePullPolicy: Always
          ports:
            - containerPort: 25565
              protocol: TCP
          env:
            - name: EULA
              value: "TRUE"
            - name: TYPE
              value: "FOLIA"
            - name: ONLINE_MODE
              value: "FALSE"
            - name: MAX_PLAYERS
              value: "1000"
          volumeMounts:
            - mountPath: /data
              name: data
          readinessProbe:
            exec:
              command:
                - mc-monitor 
                - status 
                - --host 
                - localhost 
                - --port
                - "25565"
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 18
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: longhorn
        resources:
          requests:
            storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: minecraft-server
  name: minecraft-server
  namespace: minecraft
spec:
  ports:
    - port: 25565
      targetPort: 25565
      protocol: TCP
  selector:
    app: minecraft-server
  type: ClusterIP

---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: minecraft-server
  namespace: minecraft
spec:
  entryPoints:
    - minecraft-tcp
  routes:
    - match: HostSNI(`minecraft.commonutil.com`)
      services:
        - name: minecraft-server
          port: 25565
    - match: HostSNI(`mc.commonutil.com`)
      services:
        - name: minecraft-server
          port: 25565